export const routes = {
  home: '/',
  login: '/login',
  signup: '/signup',
  productDashboard: '/product/dashboard',
  productCopilot: '/product/copilot',
  productCompetitors: '/product/competitors',
  productRoadmaps: '/product/roadmaps',
  dashboard: '/dashboard',
  ideas: '/dashboard/ideas',
  newIdea: '/dashboard/ideas/new',
  idea: (id: string) => `/dashboard/ideas/${id}`,
  copilot: '/dashboard/copilot',
  copilotWithDraft: '/dashboard/copilot?draft=1',
  copilotForIdea: (id: string) => `/dashboard/copilot?idea=${id}`,
  competitors: '/dashboard/competitors',
  gaps: '/dashboard/gaps',
  roadmaps: '/dashboard/roadmaps',
  notifications: '/dashboard/notifications',
  exports: '/dashboard/exports',
  settings: '/dashboard/settings',
  workflow: '/workflow',
  intel: '/intel',
  copilotSection: '/copilot',
  mockups: '/mockups',
  why: '/why',
  problem: '/problem',
  contact: '/contact',
  pricing: '/#pricing',
  cta: '/#cta',
} as const
