export const routes = {
  home: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  ideas: '/dashboard/ideas',
  newIdea: '/dashboard/ideas/new',
  idea: (id: string) => `/dashboard/ideas/${id}`,
  copilot: '/dashboard/copilot',
  competitors: '/dashboard/competitors',
  gaps: '/dashboard/gaps',
  roadmaps: '/dashboard/roadmaps',
  notifications: '/dashboard/notifications',
  exports: '/dashboard/exports',
  settings: '/dashboard/settings',
  workflow: '/#workflow',
  intel: '/#intel',
  copilotSection: '/#copilot',
  pricing: '/#pricing',
  cta: '/#cta',
  why: '/#why',
  mockups: '/#mockups',
  problem: '/#problem',
} as const
